/* ============================================================
   {{name}} ANIMATION PACKS, the shared part: {{name}} as a REGION CONFIG over the generic region framework
   (71-anim-0region.js owns the lookups, the pack builder, the scene registry and the full-screen scene kit). PURE classic
   script (no DOM, no fetches, nothing looked up online). Generated by `node tools/anim-pack.mjs new {{id}} "{{name}}"`.
   A region is DATA, never logic: fill the tables below, then draw the scenes and the pack files; never copy a lookup.

   LOAD ORDER. This file's name sorts BEFORE 71-anim-registry.js and 71-anim-library.js (the build concatenates src/app/*.js
   by name into ONE script scope), so at load time it may use ONLY the framework's names (animRegionDefine, animRegionSceneAdd,
   animSceneKit). Touching ANIM_SLOTS or any other registry const here throws "Cannot access ... before initialization" and the
   whole app script dies; tests/region-framework.test.mjs evaluates the files in build order and catches it. Every src/app file
   shares that one scope: the constants below are global, keep their {{ID}}_ prefix.

   WHERE THE USER IS (offline, no setting). While travelling, ctx.city is a travel city id and the matching place row decides.
   At home, the weather town (ctx.lat / ctx.lon) decides: a big or small place within its radius gives the PLACE, any row within
   {{ID}}_UNIT_KM of the position gives the {{unit_word}} (the nearest row wins, so beside a border it can be the neighbour).
   Items: a {{unit_word}} has a full-screen signature opening and a small element (priority 1); a big place a full-screen
   opening, a small place a small element (priority 1.2). A festival or the birthday (priority 2+) still wins the day.

   REGIONS MUST NOT OVERLAP. No row of this region may sit inside another region's reach ({{ID}}_UNIT_KM from its nearest row;
   the US reaches 190 km, Asia 300 km), and no other region's row inside this one's: tests/region-framework.test.mjs loops over
   every region and fails naming both and the row. Where two reaches overlap between rows, the region whose nearest row is
   NEARER wins. Fixes: move or drop the row, or lower one {{ID}}_UNIT_KM (then run the tests of both regions). NEVER add rows
   outside this region's own territory to "sharpen" its edge: that claims the neighbour's ground.

   Guide: docs/dev/ANIMATION_PACKS.md ("Regions"), docs/dev/{{ID}}_PACK.md. Gate: tests/{{id}}-pack.test.mjs (this region) and
   tests/region-framework.test.mjs (every region). Progress: `node tools/anim-pack.mjs status {{id}}`.
   ============================================================ */

/* >>> STARTER DATA: the rows below are EXAMPLES (2 units, 3 places, in the open sea where no real region reaches). Replace them
   with the real tables. `node tools/anim-pack.mjs status` warns (and `--strict` fails) while "example-" rows remain. <<<

   UNITS: { CODE: [name, group] }
     CODE   the key of the {{unit_word}} everywhere: item fields, scene keys ('{{unit_word}}:CODE'), the place rows' third column. For a
            region of countries use the ISO 3166-1 alpha-2 code ('FR', 'JP'): it is also the item's `region` and the travel id's suffix.
     name   the human name, shown under "Welcome to <name>" and in labels.
     group  one of {{groups_list}}. A group becomes a PACK ('{{id}}-<group>', one pack file) and a batch of agents: keep groups
            culturally and geographically coherent, 5 to 25 units each. A group exists only if some unit has it; every unit needs
            at least one place row below. Table order is drawing order: list neighbours together. */
const {{ID}}_UNITS = {{units_table}};

/* PLACES: [id, name, unit CODE, lat, lon, kind]
     id        lower-case letters, digits and dashes, unique in the region ('springfield-il', not 'springfield', when names repeat).
               The id plus '-' plus the lower-case country code is the TRAVEL CITY ID (the next comment).
     kind      'big'    a major city: a full-screen opening, the scene key 'place:<id>' (plays within placeKm.big, 50 km)
               'small'  a smaller city, a town or a famous place: a small symbol, B.place('<id>', ...) (plays within placeKm.small, 30 km)
               ''       an ANCHOR: no art at all. It only tells which {{unit_word}} a position is in. Add anchors along borders and through the
                        middle of large {{unit_word}}s so that "the nearest row" gives the right {{unit_word}} everywhere people live.
     lat, lon  decimal degrees (two decimals are plenty for a city). A row decides {{unit_word}}s by DISTANCE: 100 to 250 km between
               rows is typical; a {{unit_word}} with a single row only exists within {{ID}}_UNIT_KM of it.
   Pick the big places by size and fame, the small ones by what is worth a symbol. Every unit that opens needs a signature scene and an element whatever its rows are; every big place
   a scene; every small place an element: the work is the sum, so choose the list you can finish well.

   THE TRAVEL ID of a row is '<place id>-<country code, lower case>' ('tokyo-jp', 'seattle-us', 'paris-fr'): the country code is the
   unit code for a region of countries, or the `country` field below for states and provinces. It must equal the id the travel tables use
   for that city (src/app/69-travel-data.js, trPlaceTables().byId). Check one with:
     node -e "const T=new Function(require('fs').readFileSync('src/app/69-travel-data.js','utf8')+'\nreturn trPlaceTables();')();console.log(T.byId.has('paris-fr'))"
   A row whose id the travel tables lack is still reached from the home weather town; only a trip there misses it. Set the `travelId`
   hook in the config only when a whole region's ids differ from the default. */
const {{ID}}_PLACES = {{places_table}};

/* RADII. {{ID}}_UNIT_KM: beyond this distance from every row a position is in no {{unit_word}} of this region (the US 190, Asia 300).
   Rule of thumb: the largest gap an inhabited point can be from its nearest row, plus a margin; dense rows (a row every 100 km) allow
   100 to 150, sparse regions 250 to 300. Smaller is safer for the no-overlap rule and keeps the edge tight; larger covers more empty land
   and sea. {{ID}}_PLACE_KM: how close counts as "in" a big city (50) or a small place (30): the defaults fit; widen a big one only for a
   huge metropolis or an island hub. Two art places closer together than their radii: the nearer one wins. */
const {{ID}}_UNIT_KM = 150;
const {{ID}}_PLACE_KM = { big: 50, small: 30 };

/* WORLD PACK CITIES. The world pack (72-anim-pack-world.js) draws a landmark for travellers in: {{world_cities}}. List EVERY one of
   those travel ids that a row of this region maps to (its travel id, see above): while travelling there the region then matches nothing
   and the world pack's art plays. Forget one and this region's city art beats the world pack's landmark; the tests check it for every
   region and region.check({ worldCities }) names the missing id. Empty means no row maps to any of them. */
const {{ID}}_WORLD_TRAVEL = [];

/* The region: the config is the whole definition (the fields are documented in docs/dev/ANIMATION_PACKS.md, "The config"). The tables are
   read ONCE, here: finish them before this call (region.check() reports a table edited afterwards). */
const {{ID}}_REGION = animRegionDefine({
  id: '{{id}}',                          // lower-case letters and digits; its packs are '{{id}}-<group>'; never uk texas world core seasons sky moments rewards mine
  name: {{name_js}},                       // the human name
  over: {{name_js}},                       // the caption prefix over the town in the opening: "Welcome to <place>" over "<over>"
  unitWord: '{{unit_word}}',                // what a unit is called ('state', 'country', 'province'...): the item kind value and the scene key prefix ('{{unit_word}}:CODE')
  units: {{ID}}_UNITS, places: {{ID}}_PLACES,
  unitKm: {{ID}}_UNIT_KM, placeKm: {{ID}}_PLACE_KM,
  worldTravel: {{ID}}_WORLD_TRAVEL,
  placeKinds: ['small'],                 // B.place() builds only small places: the big cities come from their scenes through B.scenes() (Asia's way). ['big', 'small'] is the US's icons-first way
{{country_line}}
  // --- optional: uncomment and edit only when the region needs it ---
  // elsewhere: ['XX'],                  // units whose art lives in another pack (the US's Texas): looked up so borders stay right, never opened, no art needed
  // pseudo: { XX: { id: 'capital', name: 'The Capital', kind: 'big', group: 'north' } },   // a special unit with no art of its own that is one fixed place (the US's DC)
  // keys: { unit: 'cc', unitName: 'countryName' },   // property names in place() / where() results (default 'unit' and 'unitName')
  // fields: { unit: '{{id}}Cc' },        // item field names {kind, unit, place, size, signature} (default '{{id}}Kind', '{{field_unit}}', '{{id}}Place', '{{id}}Size', '{{id}}Signature')
  // tags: { root: '{{id}}' },            // the first tags of every item {root, unit, city}
  // priority: { unit: 1, city: 1.2 },    // a festival or the birthday (priority 2+) still wins the day
  // extra: (u) => ({}),                  // more fields for every item of unit u (the US adds state)
  // travelId: (row) => row[0] + '-xx',   // the travel city id of a row, when the default '<place id>-<country code>' does not fit
});
