# The {{name}} packs

> Skeleton generated by `node tools/anim-pack.mjs new {{id}} "{{name}}"`. Replace everything in angle brackets and every paragraph marked TODO, then delete
> this note. Make the guide read like `docs/dev/ASIA_PACK.md`. **Fill the "Cultural care" section FIRST, before any brief is made**: `brief` copies it into every brief
> (a brief made earlier carries only the general rules, and `brief` says so while the section is still the skeleton).

TODO: one paragraph: which part of the world the region covers, how many {{unit_word_plural}}, big places and small places it has, and which groups it is split into.
Every {{unit_word}} has a full-screen signature opening and a small symbol, every big place a full-screen opening, every small place a small symbol. They are ordinary packs
(read `docs/dev/ANIMATION_PACKS.md` first, "Regions") whose items all carry a `when(day, ctx)` rule, so none of them is in the ordinary daily rotation and none plays outside
the region.

| Pack | File | {{unit_word_plural}} |
| --- | --- | --- |
{{pack_rows}}

## Where the user is (offline, no setting)

`src/app/71-anim-region-{{id}}.js` (pure) holds `{{ID}}_UNITS` and `{{ID}}_PLACES` and the region config (`animRegionDefine`, see "Regions" in
`docs/dev/ANIMATION_PACKS.md`). The lookups, the builder and the scene kit are the generic framework in `src/app/71-anim-0region.js`; the region is `{{ID}}_REGION`
(`animRegion('{{id}}')`). `{{ID}}_PLACES` rows are `[id, name, {{unit_word}} code, lat, lon, kind]` (read once, when the region is defined), `kind` = `big` (a full-screen
opening), `small` (a small symbol) or `''` (an anchor, which only tells which {{unit_word}} a position is in).

- {{ID}}_REGION.unitOf(ctx): the {{unit_word}} of the nearest row within `{{ID}}_UNIT_KM` of the weather town (`ctx.lat`, `ctx.lon`). While travelling, `ctx.city` = `<place id>-<country code>`
  (the travel tables' ids) decides. Beside a border the neighbour can win. TODO: the neighbouring regions and how the edge is drawn.
- {{ID}}_REGION.place(ctx): an art place within 50 km (big) or 30 km (small).
- {{ID}}_REGION.where(ctx): where in the region (the place if there is one, else the {{unit_word}}). The opening sequence in `78-anim-wire.js` reaches it through the generic
  `animRegionWhere(animCtx())` (the title "Welcome to <place>"; a full-screen scene's own `site` is the caption under it, and `over` ("{{over}}") only prefixes the small opening items); no edit there.
- Travel: TODO which of this region's rows the world pack draws (`{{ID}}_WORLD_TRAVEL`).

## What is in a pack

| Kind | Priority | Slot | Items |
| --- | --- | --- | --- |
| {{unit_word}} | 1 | opening | a full-screen signature scene per {{unit_word}} |
| {{unit_word}} | 1 | symbol | a small element per {{unit_word}} |
| city | 1.2 | opening | one full-screen scene per big place |
| city | 1.2 | symbol | one small item per small place |

A city beats its {{unit_word}}'s art in its slot while you are there; a festival or the birthday (priority 2+) still wins the day.

## Full-screen scenes

The scenes are 1600 x 900, at most 32,000 bytes rendered, drawn in `src/app/71-anim-region-{{id}}-scenes-N.js` (an IIFE each) with the shared kit `animSceneKit()` /
`animSceneCss()` (`71-anim-0region.js`; see `docs/dev/US_PACK.md`): a scene file calls `animRegionSceneAdd('{{id}}', {key: '{{unit_word}}:<CODE>' | 'place:<id>', label, site, colour, mood, season, tags, svg})`,
and `{{ID}}_REGION.builder(group).scenes()` in each pack file turns every registered scene of that group into its opening item.

Style and craft: `.claude/skills/animation-pack/` (SKILL.md and its references). Quality gate: `node tools/anim-pack.mjs lint` (calibrated thresholds, no waivers for new work),
`node tools/anim-pack.mjs sheet ...` to look at the renders, `tests/anim-quality.test.mjs`.

## Cultural care

<!-- Region-specific care notes: write them BEFORE you make the briefs. They are appended to every scene and element brief (`node tools/anim-pack.mjs brief {{id}} ...`) after the general rules (no text, flags,
maps or borders, no political or military symbols, no identifiable people, no holy figures, sacred architecture only respectfully, disputed places neutral). Replace this comment with
what is specific here: sensitive places and how to draw them neutrally, motifs to avoid, local conventions (seasons, dress code of a building, orientation of a sacred place)
and anything a reviewer must check. Keep it to a short list of "Draw ..." and "Never draw ..." lines. -->

## Adding a place, a {{unit_word}} or a scene

1. A new place: a row in `{{ID}}_PLACES` (`big` or `small`), then its scene (`place:<id>`) or one `B.place('<id>', {...})` in the pack file of its group.
2. A new {{unit_word}}: a row in `{{ID}}_UNITS` (its group) and at least one place row, then the `{{unit_word}}:<CODE>` scene and one `B.element('<CODE>', {...})`.
3. `node tools/anim-pack.mjs status {{id}}`, then `node --test tests/anim-packs.test.mjs tests/{{id}}-pack.test.mjs tests/region-framework.test.mjs tests/anim-quality.test.mjs`.

## Making the whole region

1. `node tools/anim-pack.mjs status {{id}}` shows what is missing (no table problem, no starter row, the real `country` code when the units are not countries).
2. Fill in the "Cultural care" section above. Only then make the briefs: the section is copied into each of them.
3. `node tools/anim-pack.mjs reference --render` (and `--mode night`, `--mode dark`) once, so that no agent renders the gold standard while another does.
4. `node tools/anim-pack.mjs brief {{id}} --kind scene --out .anim-ref/briefs` (and `--kind element`) writes the task briefs for the agents and a `plan.json` to dispatch from.
5. Each agent draws its batch and passes the lint and the look gate (see the skill's `references/workflow.md`); the orchestrator proves with `node tools/anim-pack.mjs guard --owned <its files>` that only those files changed.
6. `node tools/anim-pack.mjs status {{id}} --strict` exits 0, `npm test` is green, `node build.mjs --syntax`, `node tools/privacy-scan.mjs` is clean.
