/* ============================================================
   {{name}} FULL-SCREEN SCENES, batch {{n}}. PURE classic script: it defines nothing global; it registers entries with
   animRegionSceneAdd('{{id}}', {...}). STUB generated by `node tools/anim-pack.mjs new`: no scene yet. The task brief for the agent that
   owns this file (and for every other batch) comes from `node tools/anim-pack.mjs brief {{id}} --kind scene`; the batches are
   src/app/71-anim-region-{{id}}-scenes-N.js (about 7 scenes each).

   RULES.
   - Wrap the file in an IIFE, as below: every src/app file shares ONE script scope, so a bare top-level `const K` here would clash with the
     next scene file's ("Identifier 'K' has already been declared").
   - This file sorts before the registry and the library: at load time use ONLY animSceneKit() and animRegionSceneAdd; never ANIM_SLOTS or
     any other registry const (it throws "Cannot access ... before initialization").
   - An entry is {key, id?, label, site, colour, mood, season, tags, svg}. key: '{{unit_word}}:<CODE>' (a unit's signature) or 'place:<id>'
     (a big place). label says what is drawn WITHOUT the place name (", <name>" is appended); site is the caption shown under the "Welcome to <place>"
     title of the opening: a short description of the view ("Rice terraces above a misty valley"), never just the place name again. svg() returns the INSIDE of a 1600 x 900 drawing built with the kit. B.scenes() in the pack file of the group turns every
     registered scene into its opening item (label gets ", <name>" appended; the item id is '<code>-signature' / '<place>-skyline' unless
     the entry has its own id). Style, kit and recipes: .claude/skills/animation-pack/. Gate: node tools/anim-pack.mjs lint --file <this file>.
   ============================================================ */
(function () {
  const K = animSceneKit();
  // const { U, R, rnd, lin, linU, radU, mv, full, ridge, canopy, cloud, streak, haze, rays, sun, stars, birds, shimmer, puffs, dots, lit, finish } = K;
  // animRegionSceneAdd('{{id}}', { key: '{{unit_word}}:XA', label: 'Terraced hills at dusk', site: 'Rice terraces above a misty valley', colour: 'orange', mood: 'calm', season: 'any', tags: ['landscape'],
  //   svg: () => { /* the 1600 x 900 drawing */ } });
})();
