# The {{name}} packs

> Skeleton generated by `node tools/anim-pack.mjs new {{id}} "{{name}}"`. Replace everything in angle brackets and every paragraph marked TODO, then delete
> this note. Make the guide read like `docs/dev/ASIA_PACK.md`. **Fill the "Cultural care" section FIRST, before any brief is made**: `brief` copies it into every brief
> (a brief made earlier carries only the general rules, and `brief` says so while the section is still the skeleton).

TODO: one paragraph: which part of the world the region covers, how many {{unit_word_plural}}, big places and small places it has, and which groups it is split into.
Every {{unit_word}} has a full-screen signature opening and a small symbol, every big place a full-screen opening, every small place a small symbol. They are ordinary packs
(read `docs/dev/ANIMATION_PACKS.md` first, "Regions") whose items all carry a `when(day, ctx)` rule, so none of them is in the ordinary daily rotation and none plays outside
the region.

| Pack | File | {{unit_word_plural}} |
| --- | --- | --- |
{{pack_rows}}

## Where the user is (offline, no setting)

`src/app/71-anim-region-{{id}}.js` (pure) holds `{{ID}}_UNITS` and `{{ID}}_PLACES` and the region config (`animRegionDefine`, see "Regions" in
`docs/dev/ANIMATION_PACKS.md`). The lookups, the builder and the scene kit are the generic framework in `src/app/71-anim-0region.js`; the region is `{{ID}}_REGION`
(`animRegion('{{id}}')`). `{{ID}}_PLACES` rows are `[id, name, {{unit_word}} code, lat, lon, kind]` (read once, when the region is defined), `kind` = `big` (a full-screen
opening), `small` (a small symbol) or `''` (an anchor, which only tells which {{unit_word}} a position is in).

- {{ID}}_REGION.unitOf(ctx): the {{unit_word}} of the nearest row within `{{ID}}_UNIT_KM` of the weather town (`ctx.lat`, `ctx.lon`). While travelling, `ctx.city` = `<place id>-<country code>`
  (the travel tables' ids) decides. Beside a border the neighbour can win. TODO: the neighbouring regions and how the edge is drawn.
- {{ID}}_REGION.place(ctx): an art place within 50 km (big) or 30 km (small).
- {{ID}}_REGION.where(ctx): where in the region (the place if there is one, else the {{unit_word}}). The opening sequence in `78-anim-wire.js` reaches it through the generic
  `animRegionWhere(animCtx())` (the title "Welcome to <place>"; a full-screen scene's own `site` is the caption under it, and `over` ("{{over}}") only prefixes the small opening items); no edit there.
- Travel: TODO which of this region's rows the world pack draws (`{{ID}}_WORLD_TRAVEL`).

## What is in a pack

| Kind | Priority | Slot | Items |
| --- | --- | --- | --- |
| {{unit_word}} | 1 | opening | a full-screen signature scene per {{unit_word}} |
| {{unit_word}} | 1 | symbol | a small element per {{unit_word}} |
| city | 1.2 | opening | one full-screen scene per big place |
| city | 1.2 | symbol | one small item per small place |

A city beats its {{unit_word}}'s art in its slot while you are there; a festival or the birthday (priority 2+) still wins the day.

## Full-screen scenes

The scenes are 1600 x 900, at most 32,000 bytes rendered, drawn in `src/app/71-anim-region-{{id}}-scenes-N.js` (an IIFE each) with the shared kit `animSceneKit()` /
`animSceneCss()` (`71-anim-0region.js`; see `docs/dev/US_PACK.md`): a scene file calls `animRegionSceneAdd('{{id}}', {key: '{{unit_word}}:<CODE>' | 'place:<id>', label, site, colour, mood, season, tags, svg})`,
and `{{ID}}_REGION.builder(group).scenes()` in each pack file turns every registered scene of that group into its opening item.

Style and craft: `.claude/skills/animation-pack/` (SKILL.md and its references). Quality gate: `node tools/anim-pack.mjs lint` (calibrated thresholds, no waivers for new work),
`node tools/anim-pack.mjs sheet ...` to look at the renders, `tests/anim-quality.test.mjs`.

## Cultural care

<!-- Region-specific care notes: write them BEFORE you make the briefs. They are appended to every scene and element brief (`node tools/anim-pack.mjs brief {{id}} ...`) after the general rules (no text, flags,
maps or borders, no political or military symbols, no portraits, faces, crowds or identifiable people, no holy figures, sacred architecture only respectfully, disputed places neutral). Replace this comment with
what is specific here: sensitive places and how to draw them neutrally, motifs to avoid, local conventions (seasons, dress code of a building, orientation of a sacred place)
and anything a reviewer must check. Keep it to a short list of "Draw ..." and "Never draw ..." lines.
THE REGION'S NOTES MAY ONLY BE STRICTER THAN THE GENERAL RULES, NEVER LOOSER. The general rule ALLOWS a tiny anonymous faceless silhouette as a scale cue; if this region should have none, say it in one plain line ("No person silhouette at all, of anyone")
rather than leaving two statements that seem to differ: the stricter one wins, in the briefs and in review. A note here never allows what a general rule forbids.
NAME THE SAFE MOTIFS for every sensitive unit. When you forbid a people's art, patterns, carvings, masks, dress, ceremony or the obvious national animal or instrument, an element still has to be drawn: say what IS safe, one line per sensitive unit, from
this list of kinds: a food or a drink in a plain vessel; a plant or a crop; a real animal in its habitat that is not an emblem or a mascot; a tool of daily work (a net, a paddle, a kettle); a natural feature (a reef, a cone, a waterfall); weather or the sea;
a landscape. And say what is NOT safe (a carving, a mask, a national bird used as an emblem, an instrument tied to one people). Example: "Unit XX: safe: a coconut, a fish dish, a fern. Not safe: carvings, patterns, any mask."
Also say whether the kit's sunburst (`rays()`) could read as a flag here (red and white rays read as a rising-sun ensign): the briefs already warn, add the place's own case. -->

## Scene suggestions

<!-- Optional. The briefs suggest a time of day, season, scene type and palette (scenes) and a motif kind and colour (elements) from a fixed rotation that knows nothing about the place or the care notes:
a "bridge" for a city with none, a "craft" or an "instrument" the care notes above forbid, an autumn in the tropics. Say what to use instead ONCE, here, one line per key, and every brief carries it (no agent spends a report line on
overriding the tool). Where a suggestion would still collide with the care notes, the care notes and the place win. Fields: time, season (any, spring, summer, autumn, winter: the season of the picture), type, palette (scenes); motif, colour (elements; a colour is one of blue indigo violet pink red orange amber green teal slate).
Keys are the ones `node tools/anim-pack.mjs status {{id}}` lists ("{{unit_word}}:<CODE>" for a {{unit_word}}'s signature scene AND its element, "place:<id>" for a big or small place). Example (delete the markers to use it):
- place:an-example-id: type = old town and river; palette = warm amber and rose
- {{unit_word}}:XX: season = any; motif = plant; colour = green
-->

## Adding a place, a {{unit_word}} or a scene

1. A new place: a row in `{{ID}}_PLACES` (`big` or `small`), then its scene (`place:<id>`) or one `B.place('<id>', {...})` in the pack file of its group.
2. A new {{unit_word}}: a row in `{{ID}}_UNITS` (its group) and at least one place row, then the `{{unit_word}}:<CODE>` scene and one `B.element('<CODE>', {...})`.
3. `node tools/anim-pack.mjs status {{id}}`, then `node --test tests/anim-packs.test.mjs tests/{{id}}-pack.test.mjs tests/region-framework.test.mjs tests/anim-quality.test.mjs`.

## Making the whole region

1. `node tools/anim-pack.mjs status {{id}}` shows what is missing (no table problem, no starter row, the real `country` code when the units are not countries, no overlap with another region, the travel cities of your countries that have no row).
2. Fill in the "Cultural care" section above. Only then make the briefs: the section is copied into each of them.
3. `node tools/anim-pack.mjs reference --render` once (it renders light, night and dark), so that no agent renders the gold standard while another does.
4. `node tools/anim-pack.mjs brief {{id}} --kind scene --out .anim-ref/briefs` (and `--kind element`) writes the task briefs for the agents and a `plan.json` to dispatch from; it also creates the scene file of every batch that does not exist yet and stores your `--note` texts.
5. **Commit the scaffold and the stubs** (the config, the scene stubs, the pack files, the generated test and this doc): `git add src/app/71-anim-region-{{id}}*.js src/app/72-anim-pack-{{id}}-*.js tests/{{id}}-pack.test.mjs docs/dev/{{ID}}_PACK.md && git commit -m "{{name}}: scaffold"` (`brief` prints the exact line), then run the same `brief` command again so that `plan.json` carries the base commit.
   The repo stays green while the region is drawn (`complete: false` in the config: the coverage tests are `todo`), and `guard` needs the committed scaffold as its baseline.
6. Each agent draws its batch and passes the lint and the look gate (see the skill's `references/workflow.md`); each reports its `git status --short` and its `guard --owned <its file>` output; the orchestrator proves with `node tools/anim-pack.mjs guard --owned <the files of ALL agents that ran in this tree>` that only those files changed (one agent alone: its own git worktree).
7. When everything is drawn and lint-clean: `node tools/anim-pack.mjs status {{id}} --declare-complete` sets `complete: true` in the config (the coverage tests become hard failures; it refuses while anything is missing), then `node tools/anim-pack.mjs status {{id}} --strict` exits 0, `npm test` is green, `node build.mjs --syntax`, `node tools/privacy-scan.mjs` is clean.
