/* ============================================================
   ANIMATION PACK "{{id}}-{{group}}": the {{group}} group of {{name}}. PURE classic script (no DOM, no fetches). A small symbol per
   {{unit_word}} (B.element) and one per small place (B.place); the full-screen scenes of the group come from the scene files
   (src/app/71-anim-region-{{id}}-scenes-N.js) through B.scenes(). Built with the builder of the region config
   (71-anim-region-{{id}}.js). Generated by `node tools/anim-pack.mjs new`. Gate: tests/{{id}}-pack.test.mjs,
   tests/anim-packs.test.mjs and the lint (node tools/anim-pack.mjs lint --file <this file>). Style and craft:
   .claude/skills/animation-pack/references/small-icons.md.
   ============================================================ */
(function () {
  const B = {{ID}}_REGION.builder('{{group}}');
  B.scenes();   // every registered full-screen scene of this group becomes its opening item (a {{unit_word}} signature or a big city). Never remove.
  // Small elements: svg() returns the INSIDE of a 64 x 64 drawing, theme classes only (fills k c s w m, strokes lk lc lm lw, no hex colours),
  // 1 to 3 staggered x-* motions. The builder adds the id prefix ('<code>-<id>' / '<place>-<id>'), the label suffix, tags, slot, priority and when rule.
  // One element per {{unit_word}} that opens and one per small place of this group:
{{todo_lines}}
  // The pack registers once it has an item (an empty pack is not registered: animRegisterPack answers {ok: false}); its id must be '{{id}}-{{group}}'.
  animRegisterPack(B.pack({ id: '{{id}}-{{group}}', name: {{pack_name_js}}, description: {{pack_desc_js}} }));
})();
