// The {{name}} animation packs ({{id}}): src/app/71-anim-region-{{id}}.js (the tables and the region config), 71-anim-region-{{id}}-scenes-*.js (the
// full-screen scenes) and 72-anim-pack-{{id}}-*.js (the pack files). Generated by `node tools/anim-pack.mjs new {{id}} "{{name}}"` and DATA-DRIVEN: everything
// is read from the region's own tables, so this file needs no edit when the tables grow. It asserts that every {{unit_word}} that opens has a full-screen
// signature and an element, every big place a full-screen opening, every small place an element, that the lookups send every position and every trip to the
// right art, and that nothing plays away from the region. Until the scenes and elements exist these tests FAIL on purpose: `node tools/anim-pack.mjs status {{id}}`
// lists what is missing. The rules that hold for EVERY region (sound tables, packs named <id>-<group>, no row inside another region's reach, unique travel ids,
// the world pack's cities) are loops over ANIM_REGIONS in tests/region-framework.test.mjs. The art itself is gated by tests/anim-packs.test.mjs and the lint
// (tests/anim-quality.test.mjs). Synthetic data only.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { animRegistryFiles } from '../tools/lib/anim-sources.mjs';

const APP = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'app');
const NAMES = ['ANIM_REGIONS', 'animRegion', 'animPack', 'animPacks', 'animSpecialPick', 'animDailyPick'];
const body = animRegistryFiles(APP).map(f => readFileSync(join(APP, f), 'utf8')).join('\n;\n');   // the animation files in the order the build concatenates them
// eslint-disable-next-line no-new-func
const R = new Function(`"use strict";\n${body}\nreturn { ${NAMES.join(', ')} };`)();

const REGION = R.animRegion('{{id}}');
if (!REGION) throw new Error('the region "{{id}}" is not registered: does src/app/71-anim-region-{{id}}.js call animRegionDefine({ id: \'{{id}}\', ... })?');
const F = REGION.fields, WORD = REGION.unitWord;
const day = '2026-10-05';   // a Monday: no festival
const HINT = '   (node tools/anim-pack.mjs status {{id}} lists everything that is missing)';
const items = R.animPacks().filter(p => REGION.owns(p.id)).flatMap(p => p.items);
const opens = Object.keys(REGION.units).filter(u => !REGION.elsewhere.includes(u));              // the units that need art
const arts = REGION.places.filter(p => p[5] && !REGION.elsewhere.includes(p[2]));               // the big and small places that need art
const at = (p) => ({ lat: p[3], lon: p[4] });
const cityItems = (id) => items.filter(i => i[F.kind] === 'city' && i[F.place] === id);

test('{{id}}: the region is defined and its tables are sound', () => {
  const world = [...new Set((R.animPack('world') || { items: [] }).items.map(i => i.city))];
  assert.deepEqual(REGION.check({ worldCities: world }), []);
  assert.ok(opens.length > 0 && REGION.groups.length > 0, 'no unit');
  for (const g of REGION.groups) assert.ok(R.animPack('{{id}}-' + g) || !opens.some(u => REGION.units[u][1] === g), `group ${g}: its pack {{id}}-${g} is not registered` + HINT);
});

test('{{id}}: every {{unit_word}} that opens has a full-screen signature opening and an element', () => {
  for (const u of opens) {
    const mine = items.filter(i => i[F.kind] === WORD && i[F.unit] === u);
    assert.ok(mine.some(i => i.slot === 'opening' && i[F.signature] && i.full), `${u}: a full-screen signature opening is missing` + HINT);
    assert.ok(mine.some(i => i.slot === 'symbol' && !i[F.signature]), `${u}: an element is missing` + HINT);
  }
});

test('{{id}}: every big place has a full-screen opening, every small place an element', () => {
  for (const p of arts) {
    const mine = cityItems(p[0]);
    assert.equal(mine.length, 1, `${p[0]}: exactly one item (${p[5] === 'big' ? 'a full-screen opening' : 'an element'})` + HINT);
    assert.equal(mine[0].slot, p[5] === 'big' ? 'opening' : 'symbol', p[0]);
    assert.equal(!!mine[0].full, p[5] === 'big', `${p[0]}: only big places are full screen`);
  }
});

test('{{id}}: every registered scene is built into a pack (no dead art)', () => {
  for (const key of Object.keys(REGION.scenes)) {
    const [kind, ref] = key.split(':');
    const mine = kind === 'place' ? cityItems(ref) : items.filter(i => i[F.kind] === WORD && i[F.unit] === ref && i[F.signature]);
    assert.ok(mine.some(i => i.full), `${key}: a scene is registered but no pack item uses it: does the pack file of its group call B.scenes()?`);
  }
});

test('{{id}}: items are unique, animated and gated by a when() rule', () => {
  const refs = new Set(), svgs = new Set();
  for (const it of items) {
    assert.equal(typeof it.when, 'function', it.ref);
    assert.ok(Array.isArray(it.region) && it.region.length === 1 && /^[A-Z]{2}$/.test(it.region[0]), `${it.ref}: region`);
    assert.ok(!refs.has(it.ref), `dup ${it.ref}`); refs.add(it.ref);
    const s = it.svg({});
    assert.ok(!svgs.has(s), `${it.ref} draws the same as another item`); svgs.add(s);
    assert.match(s, /class="[^"]*\bx-[a-z]/, `${it.ref} moves`);
  }
});

test('{{id}}: where the user is decides what plays (at home and while travelling)', () => {
  const pick = (slot, ctx, look) => R.animSpecialPick(slot, day, look || {}, ctx);
  for (const p of arts) {
    const [id, , u, , , kind] = p, slot = kind === 'big' ? 'opening' : 'symbol';
    assert.equal((REGION.place(at(p)) || {}).id, id, `${id}: its own position is in it (two rows at the same spot?)`);
    const home = pick(slot, at(p));
    assert.equal(home && home[F.place], id, `${id}: the ${slot} at home` + HINT);
    if (REGION.units[u]) {   // a big place has no symbol: the {{unit_word}} element plays; a small place has no opening of its own: the signature plays
      const other = pick(kind === 'big' ? 'symbol' : 'opening', at(p));
      assert.ok(other && other[F.kind] === WORD && other[F.unit] === u && (kind === 'big' ? !other[F.signature] : other[F.signature]), `${id}: the ${kind === 'big' ? '{{unit_word}} element' : '{{unit_word}} signature'} plays in the other slot` + HINT);
    }
    const city = REGION.travelId(p);
    if (REGION.worldTravel.includes(city)) { assert.equal(REGION.place({ city }), null, `${city}: the world pack's`); continue; }
    const trip = pick(slot, { city });
    assert.equal(trip && trip[F.place], id, `${id}: the ${slot} while travelling (${city})` + HINT);
    assert.equal(REGION.unitOf({ city }), u, city);
  }
  for (const u of opens) {
    const anchor = REGION.places.find(p => p[2] === u && !p[5]);
    for (const p of REGION.places.filter(x => x[2] === u)) assert.equal(REGION.unitOf(at(p)), u, `${p[0]} is in ${u}`);
    if (!anchor) continue;
    const sig = pick('opening', at(anchor)), el = pick('symbol', at(anchor));
    assert.ok(sig && sig[F.unit] === u && sig[F.signature] && sig.full, `${u}: the signature plays at an anchor row (${anchor[0]})` + HINT);
    assert.ok(el && el[F.unit] === u && !el[F.signature], `${u}: the element plays at an anchor row (${anchor[0]})` + HINT);
  }
  const first = arts[0];
  if (first) {
    const pack = (cityItems(first[0])[0] || {}).pack;
    const off = pick(first[5] === 'big' ? 'opening' : 'symbol', at(first), { packsOff: [pack] });
    assert.ok(!off || off.pack !== pack, 'a pack switched off plays nothing');
  }
});

test('{{id}}: nothing plays away from the region', () => {
  const candidates = [{ lat: 0, lon: 0 }, { lat: 0, lon: -140 }, { lat: -75, lon: 0 }, { lat: 75, lon: -40 }, { lat: 20, lon: -170 }, { lat: -30, lon: 100 }, { lat: 55, lon: -100 }, { lat: -20, lon: -60 }];
  const away = candidates.filter(c => REGION.unitOf(c) === '').slice(0, 4);
  assert.ok(away.length >= 3, 'the region reaches almost everywhere: check unitKm and the rows');
  for (const c of away) {
    assert.equal(REGION.place(c), null); assert.equal(REGION.where(c), null);
    for (let i = 0; i < 24; i++) {
      const d = `2026-${String(1 + (i % 12)).padStart(2, '0')}-${String(1 + i % 28).padStart(2, '0')}`;
      for (const slot of ['opening', 'symbol']) {
        const it = R.animDailyPick(slot, d, {}, c);
        assert.ok(!it || !REGION.owns(it.pack), `${d} ${slot} at ${c.lat}, ${c.lon}: no item of {{id}} away from it`);
      }
    }
  }
  for (const c of [{}, null, undefined, { lat: null, lon: null }, { lat: NaN, lon: 10 }]) { assert.equal(REGION.unitOf(c), '', JSON.stringify(c)); assert.equal(REGION.where(c), null); }
});
